---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Debian"
 
  - name: install openssh-server package
    apt:
      name: openssh-server
      state: latest
    when: ansible_distribution == "Debian"
